name: oci_run
on: push
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      compartment-id: ocid1.compartment.oc1..aaaaaaaat7hizmoey6s6y252rrig3kxh3du3z27nlllaefm2x423x6pstbgq
    steps:
      - name: Retrieve the display name and shape of the instances in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.3.1
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ env.compartment-id }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'    
      - name: List the display name and shape of the instances in my compartment
        run: |
          echo ${{ steps.find-compartment-id.outputs.raw_output }} | jq .
