name: deploy
on:
  push:
    paths:
      - 'deploy*'
    branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: execute remote ssh & deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}        
          script: |
            rm -rf MySQL_install/
            git clone https://github.com/khkwon01/MySQL_install.git
            ls -al
